export const ADD_SIGN_TO_PLAYLIST = 'ADD_SIGN_TO_PLAYLIST';
export const REMOVE_SIGN_FROM_PLAYLIST = 'REMOVE_SIGN_FROM_PLAYLIST';
export const MOVE_SIGN_IN_PLAYLIST = 'MOVE_SIGN_IN_PLAYLIST';

export const CREATE_NEW_PLAYLIST = 'CREATE_NEW_PLAYLIST';
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';

export const CREATE_NEW_SIGN = 'CREATE_NEW_SIGN';
export const UPDATE_SIGN = 'UPDATE_SIGN';
export const DELETE_SIGN = 'DELETE_SIGN';
